### ISSUE TITLE
using bbox_inches='tight' with `m.savefig` results in a blank export

### ISSUE THREAD

**Issue by yun881201** [raphaelquast/EOmaps#155]
After update, savefig gives me black paper.

my code:
```python
m = Maps(crs=5179, frameon=False)
~
m.snapshot(clear=True)
m.savefig('name.png', dpi=300, bbox_inches='tight', pad_inches=0.1, facecolor='auto', edgecolor='auto')
plt.close()   
```
snapshot works well but savefig gives me black paper

**Comment by raphaelquast** [comment]
OK, the reason was that using `bbox_inches='tight'` involves an intermediate draw to determine the bbox. 
This draw however does not update the gui which in turn results in empty cached background layers and subsequently in a empty figure export.

I implemented a fix for this which will also go into the next release. 
Thanks for highlighting this problem!

**Comment by yun881201** [comment]
Thanks! Can I know the meaning of parameter in '0_map': [0.00716, 0.0059, 0.98569, 0.9882] ?
I guess [0.00716, 0.0059, 0.98569, 0.9882] = [left up location , right down location], but when I set [0, 0, 1, 1], I got the figure with upside margin. And I also tried another setting [0, - 0.03, 1, 1.03], but I didn't get the figure without margin...

**Comment by yun881201** [comment]
With this set "m.apply_layout({'figsize': [4.17, 3.84], '0_map': [0, 0, 1, 1]})", I can get what I want. The parameter setting is quite difficult, since parameter setting does not apply to the picture like my intuition.

**Comment by yun881201** [comment]
One more question. Before update, I can save the figure without seeing in jupyter notebook cell with code "plt.close()". This function is good for me working with big size notebook. But, after update, this function is not working. Can I save the figure without seeing it in the cell ?

**Comment by raphaelquast** [comment]
OK, first, the meaning of the values is  `["left", "bottom", "width", "height"]`  in figure coordinates (e.g. 0-1)

However, the problem here is more involved since maps have to **preserve the aspect-ratio** so fixing both the x- and y- size of a geo-axes does not work as you might expect since they are not independent of each other...

The values of the layout-dict are not really intended to be adjusted manually.... it is meant as a "save" of an existing layout (which will naturally preserve aspects etc.)

What I meant was using the layout manager like this (e.g. a completely manual approach) and then obtain the dict with appropriate values using `m.get_layout()`
<img src=https://user-images.githubusercontent.com/22773387/225011500-e36d388a-cd06-4c5f-aa62-de7058468203.gif width=30%>

Anyways, I can try to release the bugfix version later today then you can skip searching for workarounds and use the code as you always did instead 😅 

---- 

For your second question ... this should be possible by selecting a non-gui backend or using (`%%capture`) but I'd need to see what you're using to get an idea where your problem comes from... 

If you open a dedicated [Discussion](https://github.com/raphaelquast/EOmaps/discussions/categories/q-a)  I can try to help...  
(I like to keep this issue clean and also to make answers/discussions on more general questions accessible for others as well) ?

**Comment by raphaelquast** [comment]
Hey @yun881201, if you update to EOmaps v6.2, using `m.savefig()` with `bbox_inches='tight'` should work as expected!
(would be nice if you let me know if all works on your side as well)

**Comment by yun881201** [comment]
Hi @raphaelquast. I'm back. Thank you very much. That's good news for me. I'll try and let you know.

**Comment by yun881201** [comment]
@raphaelquast 
I checked the code m.savefig() with bbox_inches='tight' in v6.2 and v6,2,1. But the code resulted in a blank export. Is there some information you should know for your work? Then, I'll give you the information.

**Comment by yun881201** [comment]
Using code %%capture to is a good solution for preventing plot from showing in jupyter notebook cell!

**Comment by raphaelquast** [comment]
Hey @yun881201 
thanks for opening a discussion for the second question!


Concerning `bbox_inches="tight"`... that's quite strange... for me it works just as expected when using the `Spyder IDE` or `Jupyter Lab`

```python
from eomaps import Maps

m = Maps(crs=5179, frameon=False)
m.add_feature.preset.coastline()
m.add_feature.preset.ocean()

m.savefig(r'name.png', bbox_inches="tight", dpi=300)
```
<img src=https://user-images.githubusercontent.com/22773387/227127866-afe293b6-edc8-4403-9bce-9d7015fab348.png width=20%>


To find out what's going on:
1. can you confirm that the code above does not work for you? 
2. ```

**Comment by yun881201** [comment]
1. The code above work for me perfectly. 
2. OS is window10 Enterprise. 
3.  In module://matplotlib_inline.backend_inline, my code give me a map, not a blank! But the map figure has strange margins (left margin is big. And right and bottom does not exist) and no display of some m.add_gdf. 

FYI 

My full code is

    m = Maps(crs=5179, frameon=False)
    m.set_data(
        data=data,  
        parameter="value", 
        x="lon",  
        y="lat",  
        crs=4326,
    )  

    m.set_shape.geod_circles(radius=50)
    m.plot_map(fc="red", alpha=1, lw=0 ,zorder=6)
    m.set_extent([124.598822,131.87222222,38.70000000,33.10000000]) 
    m.add_feature.physical.ocean(scale=50, fc="#97b6e1")
    m.add_feature.cultural.admin_0_boundary_lines_land(scale=10, fc="none", ec="k", lw=0.7, ls=":", zorder=4)
    gdf = m.add_feature.cultural.admin_0_countries.get_gdf(scale=50) 
    m.add_gdf(gdf[gdf.ADM0_A3 == "KOR"], facecolor="#97b6e1", edgecolor="#97b6e1")
    m.add_gdf(somegdf1, facecolor="#97b6e1", edgecolor="#97b6e1")
    m.add_gdf(somegdf2, fc="white", ec="white", lw=1, zorder=2)
    m.add_gdf(somegdf3, fc="white", ec="grey", lw=0.1, zorder=3)
    m.savefig('name.png',bbox_inches='tight', dpi=300)

**Comment by raphaelquast** [comment]
Hey, 
thanks!
please provide a working reproducible example (e.g. incl. `data` and `somegdf`, etc.) ... otherwise it is impossible to reproduce your error!

Just from the code above, it seems that you plot the gdf's either in white or in the ocean-color... are you certain that they not just seem invisible because they look like land/ocean? 

---- 

While investigating this I did indeed find a problem in the internals of eomaps that can cause the ordering of artists **at the same zorder** to change randomly instead of following the insertion-order....

This was a stupid mistake and it is fixed in the next version (to be released soon)...

In the meantime, assigning an explicit zorder should avoid this.

---- 

- What do you mean by "left margin is big"? Do you talk about the exported image or the jupyter-notebook cell output? 
(those are 2 different things since `bbox_inches='tight'` will result in different margins for the exported figure)

**Comment by raphaelquast** [comment]
Hey @yun881201 
Updating to v6.3 should fix (among other things) any remaining issues concerning the stacking order of features!

**Comment by yun881201** [comment]
Hey @raphaelquast 
v6.3 fixed every issue I have! Thank you very much for your quick fixing.

**Comment by raphaelquast** [comment]
@yun881201 Awesome! Thanks for taking the time to report the problems, much appreciated!
